## Numpy array and basics
learn about numpy with chai aur code

In [2]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [6]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)



Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.031139135360717773

 Numpy operation time:  0.0009281635284423828


### creating array from scratch

In [40]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

random2 = np.random.random_integers(6, size=(4,4))      #6 is the upper limit of integers being printed
print(random2)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

seq2 = np.arange(1, 28, 3)
print(seq2)




zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.39265763 0.87953095 0.23664782]
 [0.05209327 0.13902589 0.69559438]]
[[3 2 2 4]
 [5 1 6 4]
 [2 6 1 1]
 [5 3 1 6]]
sequnce array: 
 [ 0  2  4  6  8 10]
[ 1  4  7 10 13 16 19 22 25]


C:\Users\harsh\AppData\Local\Temp\ipykernel_21940\3942570127.py:13: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  random2 = np.random.random_integers(6, size=(4,4))      #6 is the upper limit of integers being printed


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix, matrix.ndim)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor, tensor.ndim)

tens2 = np.array([
                [[1, 2, 3], [4, 5, 6]],
                [[11, 22, 33], [44, 55, 66]]
                  ])
print("tens2: \n", tens2, tens2.ndim)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]] 2
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3
tens2: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]] 3


### Array properties

In [21]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [24]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)



Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Again reshaping more trial

In [24]:
orig = np.arange(1, 101, 1)
print(orig)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
print(orig.size)   
reshaped = orig.reshape((2,50))     #reshape must be equal to the size of orig
print(reshaped)

100
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37  38  39  40  41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
   87  88  89  90  91  92  93  94  95  96  97  98  99 100]]


In [35]:
print(orig.flatten(), orig.flatten().shape)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] (100,)


In [39]:
simple_matric = np.random.randint(20, size=(4, 4))
print(simple_matric)

print(simple_matric.T)

[[11 17  2  9]
 [15 12  7 12]
 [16 13  9 10]
 [12 15  1  3]]
[[11 15 16 12]
 [17 12 13 15]
 [ 2  7  9  1]
 [ 9 12 10  3]]
